### ISSUE TITLE
CMS cannot edit CSS

### ISSUE THREAD

**Issue by nox7** [FootbridgeMediaPensacola/Footbridge-CMS#1]
The CMS should not allow editing of CSS files, but .scss and .sass files should be editable through the template manager.

Feature design:
- Before allowing the SASS files to be loaded, the following criteria must be met
- + Check all .scss files for their modified time. Store the most recent (greatest integer) modified unix time.
- + Check any .css files modified time, store all of the CSS modified times in an array
- + Compare the modified times. If ANY CSS file's modified time is greater than 5 minutes (60 * 5) ahead of ANY SASS file, then DO NOT load the .scss files into the template manager. This means someone has manually edited the CSS file and editing any SASS file would cause it to be overwritten
- Add the .scss files to the front end template manager
- Allow them to be saved and new ones created
- In the save file controller (should be the same PHP controller that saves all the other template files), add an if statement for if a SASS file is saved. This will be a precursor for the CMS SASS parsing feature in the future.

**Comment by nox7** [comment]
Merge completed, will branch out to parse SASS using php-sass-parser repo eventually

**Comment by nox7** [comment]
The other half is part of the same issue

**Comment by nox7** [comment]
Using: https://github.com/scssphp/scssphp

Whenever any SCSS/SASS file is edited, run the parser on all .scss or .sass files THAT DO NOT BEGIN with an _

**Comment by johnellison919** [comment]
#4 The basics of this are working, but there are a few things that still need doing before this is ready to go. 

- We need a way to notify the user of any compiling errors
- The variable names could definitely be more descriptive of what they're for or what they do
- It seems that this update has messed with the saving feature. It requires you to save twice to ensure the changes are made.
- We might need to look at the way we have stylesheet files grouped. One example is the fa.scss file requiring that the font-aw folder and its files are present to compile.
