### ISSUE TITLE
v3+ Page Sorting

### ISSUE THREAD

**Issue by johnellison919** [FootbridgeMediaPensacola/Footbridge-CMS#46]
When the CMS was using JSON databases instead of SQL, pages in the page editor would align alphabetically. They're now aligned through creation date. It's just a personal preference, but having pages sort alphabetically again would potentially make navigating through pages easier -  especially on larger sites.

**Comment by nox7** [comment]
Fix by commit 5b120ce085d48bf5f7e668423ca64df995e668f9 This was actually a bug with incorrect class constants being used.
