### ISSUE TITLE
ODT File Parser Overwrite

### ISSUE THREAD

**Issue by johnellison919** [FootbridgeMediaPensacola/Footbridge-CMS#48]
Currently, if you try to create a page with the ODT File Parser and it already exists, you get an error/warning message that tells you that the page already exists. It would be nice to be able to overwrite it directly from that error/warning modal, rather than having to go delete the page, then re-creating it again.

**Comment by nox7** [comment]
Feature design:
- When the error is returned, make a modal appear requesting permission to overwrite or simply to cancel
- If overwrite is chosen, resent the same form POST - but include a new parameter "allow-overwrite" which tells the Controller to simply overwrite the page if it exists

**Comment by nox7** [comment]
Merged into master
