### ISSUE TITLE
FlexParser converting all phone numbers to {{ phoneNumber which=1 }}

### ISSUE THREAD

**Issue by DrPersson** [FootbridgeMediaPensacola/Footbridge-CMS#55]
For websites with multiple phone numbers this flattens them to the first number.
My recommendation is to have this behavior as default, but give the option of:
- disabling this behavior
- choose which numbers should translate to which number shortcodes in the CMS

**Comment by nox7** [comment]
Will update the flex parser to simply ignore phone numbers. This can be handled in the filters
